Solution.Web/Controllers/Formation/FormationController.cs
using RecrutementService.Services;
using Solution.Domain;
using Solution.Domain.Entities;
using Solution.Service.Services;
using Solution.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Net.Mail;
using System.Net;

namespace Solution.Web.Controllers.Formation
{
    public class FormationController : Controller
    {
        ApplicationService aps = new ApplicationService();
        FormationService ts = new FormationService();
        // GET: Formation
        public ActionResult Index()
        {

            System.Net.Http.HttpClient Client = new System.Net.Http.HttpClient();
            Client.BaseAddress = new Uri("http://localhost:9080");
            Client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            System.Net.Http.HttpResponseMessage response = Client.GetAsync("pidevADVYTEAM-web/formation").Result;
            if (response.IsSuccessStatusCode)
            {
                ViewBag.result = response.Content.ReadAsAsync<IEnumerable<formation>>().Result;
            }
            else
            {
                ViewBag.result = "error";
            }
            return View();
        }

        // GET: Formation/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Formation/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Formation/Create
        [HttpPost]
        public ActionResult Create(FormationModel f)
        {
            HttpClient client = new HttpClient();

            HttpRequestMessage requestMessage = new HttpRequestMessage(HttpMethod.Post, "http://localhost:9080/pidevADVYTEAM-web/formation/new");
            string json = new JavaScriptSerializer().Serialize(new
            {
                nom = f.nom,
                descreption = f.descreption,
                date = f.date,
                nbrplace = f.nbrplace,
                lieu = f.lieu,



            }
                );
            requestMessage.Content = new StringContent(json, Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.SendAsync(requestMessage).GetAwaiter().GetResult();
            return RedirectToAction("Index");
        }

        // GET: Formation/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Formation/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Formation/Delete/5

        public ActionResult Delete(int id)
        {
            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:9080");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage responce = Client.DeleteAsync("/pidevADVYTEAM-web/formation/" + id).Result;
            return RedirectToAction("Index");
        }

        // POST: Formation/Delete/5
        /* [HttpPost]
         public ActionResult Delete(int id, FormCollection collection)
         {
             try
             {
                 // TODO: Add delete logic here

                 return RedirectToAction("Index");
             }
             catch
             {
                 return View();
             }
         }*/


        //////////////////////////////////////////////// application ////////////////////////////////
        ///
        public ActionResult Apply()
        {
            var formations = ts.GetMany();
            ViewBag.TestId = new SelectList(formations, "id", "nom");

            /*var offres = OS.GetMany();
            ViewBag.Offre_Id = new SelectList(offres, "Offre_Id", "Offre_Name");*/

            return View();
        }

        // POST: Question/Create
        [HttpPost]
        public ActionResult Apply(ApplicationModel qm)
        {
            application q = new application();

            q.Nom = qm.Nom;
            q.Prenom = qm.Prenom;

            q.idFormation = qm.idFormation;

            aps.Add(q);
            aps.Commit();
            return RedirectToAction("Index");

        }
        public ActionResult Showapp()
        {
            return View(aps.GetMany());
        }

        [HttpPost]
        public ActionResult Index(string filtre)
        {
            var list = aps.GetMany();


            // recherche
            /* if (!String.IsNullOrEmpty(filtre))
             {
                 list = list.Where(m => m.Name.ToString().Equals(filtre)).ToList();
             }*/

            return View(list);



        }
        [HttpPost]
        public ActionResult Confirmer(application p)
        {
            application p1 = aps.GetById(p.AppId);
            p1.ApplicationStatus = p.ApplicationStatus;


            if (ModelState.IsValid)
            {
                aps.Update(p1);
                aps.Commit();
                var verifyurl = "/Signup/VerifiyAccount/";
                var link = Request.Url.AbsolutePath.Replace(Request.Url.PathAndQuery, verifyurl);

                var fromEmail = new MailAddress("fatma.dayeg@esprit.tn", "AdvyTeam");
                var toEmail = new MailAddress("chniti.marwen@gmail.com");
                var FromEmailPassword = "172jft1681";

                string subject = "Response On Formation Application";

                string body = "We have respond on your Formation application! Go check your Result. " +
                    "<br/><a href = '" + link + "'>" + link + "</a>";

                var smtp = new SmtpClient
                {
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    UseDefaultCredentials = false,
                    Credentials = new NetworkCredential(fromEmail.Address, FromEmailPassword),
                    Timeout = 20000
                };
                using (var message = new MailMessage(fromEmail, toEmail)
                {
                    Subject = subject,
                    Body = body,
                    IsBodyHtml = true

                }) smtp.Send(message);
                return RedirectToAction("Showapp");
            }
            return RedirectToAction("Showapp");
        }
        public ActionResult Confirmer(int id)
        {

            application t = aps.GetById(id);
            if (t == null)
            {
                return HttpNotFound();
            }
            return View(t);
        }

        public ActionResult Supprimer(int id, application p)
        {

            p = aps.GetById(id);
            aps.Delete(p);
            aps.Commit();
            return RedirectToAction("Showapp");
        }
        public ActionResult ShowAppCand()
        {
            return View(aps.GetMany());
        }

        [HttpPost]
        public ActionResult ShowAppCand(string filtre)
        {
            var list = aps.GetMany();


            // recherche
            /* if (!String.IsNullOrEmpty(filtre))
             {
                 list = list.Where(m => m.Name.ToString().Equals(filtre)).ToList();
             }*/

            return View(list);

        }
    }
}

Solution.Web/Controllers/Formation/TestController.cs
using Solution.Domain;
using Solution.Domain.Entities;
using Solution.Service.Services;
using Solution.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Solution.Web.Controllers.Formation
{
    public class TestController : Controller
    {
        FormationService cs = new FormationService();
        QuestionService iqs = new QuestionService();
        public ActionResult Index()
        {

            /* int user = Int16.Parse(User.Identity.GetUserId());
             var q = itm.GetAll();*/
            {
                FormationModel tm = new FormationModel();
                formation c = new formation();
                List<FormationModel> l = new List<FormationModel>();
                List<question> lq = new List<question>();
                c = cs.GetAll().OrderByDescending(t => t.questions.Count).First();
                c.id = tm.id;
                tm.nom = c.nom;
              
                lq = c.questions.OrderBy(x => Guid.NewGuid()).Take(20).ToList();
                tm.questions = lq;
                l.Add(tm);

                return View(l);
            }

        }

        // GET: Test/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Test/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Test/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Test/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Test/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Test/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Test/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult TestResult()
        {
            {
                FormationModel tm = new FormationModel();
                formation c = new formation();
                List<FormationModel> l = new List<FormationModel>();
                List<question> lq = new List<question>();
                c = cs.GetAll().OrderByDescending(t => t.questions.Count).First();
                tm.nom = c.nom;
                
                lq = c.questions.OrderBy(x => Guid.NewGuid()).Take(20).ToList();
                tm.questions = lq;
                l.Add(tm);

                return View(l);
            }
        }
        public ActionResult TestLang()
        {
            {
                FormationModel tm = new FormationModel();
                formation c = new formation();
                List<FormationModel> l = new List<FormationModel>();
                List<question> lq = new List<question>();
                c = cs.GetAll().OrderByDescending(t => t.questions.Count).First();
                tm.nom = c.nom;

                lq = c.questions.OrderBy(x => Guid.NewGuid()).Take(20).ToList();
                tm.questions = lq;
                l.Add(tm);

                return View(l);
            }
        }
        public ActionResult TestPsy()
        {
            return View();
        }
    }
}

Solution.Web/Views/Formation/Apply.cshtml
@model Solution.Domain.Entities.application

@{
    ViewBag.Title = "Apply";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Apply</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Confirm your informations !</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <h4>Test Name</h4>
    <div class="col-md-10">
        @Html.DropDownList("idFormation", (SelectList)ViewData["TestId"])
        @Html.ValidationMessageFor(model => model.idFormation)
    </div>

    <div class="form-group">
        <h4>Name</h4>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <h4>Last Name</h4>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Prenom, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Prenom, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <p>
            <input type="submit" value="Create" class="btn btn-lg btn-thm" />
            <button class="btn btn-lg btn-thm">@Html.ActionLink("Cancel", "Index")</button>
        </p>
    </div>
</div>
    <br />

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Solution.Web/Views/Formation/Confirmer.cshtml
@model Solution.Domain.Entities.application
@{
    ViewBag.Title = "Confirmer";
    Layout = "~/Areas/Administrateur/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Confirmer</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <h4>Please do confirm the applicant status</h4>

        @Html.HiddenFor(model => model.AppId)

        <div class="form-group">

            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationStatus, "", new { @class = "text-danger" })
            </div>
        </div>







        <div class="form-group">
            <div class="row">
                <div class="col-md-offset-2 col-md-6">
                    <input type="submit" value="Confirm" class="btn btn-lg btn-thm" />

                </div>
                <div class="col-md-offset-2 col-md-6">
                    <button class="btn btn-lg btn-thm"> @Html.ActionLink("Cancel", "ShowApp")</button>
                </div>
            </div>
        </div>
    </div>

}

Solution.Web/Views/Formation/Create.cshtml
@model Solution.Web.Models.FormationModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FormationModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descreption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descreption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descreption, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.etat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.etat)
                    @Html.ValidationMessageFor(model => model.etat, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lieu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lieu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lieu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nbrplace, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nbrplace, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nbrplace, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Solution.Web/Views/Formation/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Liste Des Evaluation</title>
</head>

<body>
    @*<a href="">add evaluation</a>
        <table class="table table-striped" cellpadding="2" cellspacing="2" border="1">
            <tr>
                <th>Id </th>
                <th>Titre</th>
                <th>Description</th>

            </tr>
            @foreach (var p in ViewBag.result)
            {
                <tr>
                    <td>@p.id</td>
                    <td>@p.nom</td>
                    <td>@p.descreption</td>
                   <td> <a href="@Url.Action("Delete", "Formation", new { id = @p.id })" class="btn btn-tool" data-widget="remove" onclick="return confirm('Are you sure you want to delete this item?');">
                        <i class="fas fa-trash"></i>
                    </a>
                    </td>
                </tr>

            }*@


    </table>

    <div class="col-xl-9">
        <div class="row">
            <div class="col-lg-12">
                <h4 class="mb30">Job List</h4>
            </div>


            <div class="col-lg-12">
                <div class="cnddte_fvrt_job candidate_job_reivew">
                    <div class="table-responsive job_review_table">
                        <table class="table">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">Formation Title</th>
                                    <th scope="col"></th>
                                    <th scope="col">Description</th>
                                    <th scope="col">Date </th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var p in ViewBag.result)
                                {
                                    <tr>
                                        <th scope="row">
                                            <img class="img-fluid" src="https://www.theatre-contemporain.net/images/upload/thumbs/L255-H255/thumb-Le-Vivier-FESTIVAL-ARTISTIQUE-POPULAIRE-SOCIAL-EDUCATIF-22a-5d370fe873477.jpg" alt="">
                                        </th>
                                        <td>
                                            <h4>@p.nom</h4>
                                           
                                            <ul>
                                                <li class="list-inline-item"><a href="#"><span class="flaticon-location-pin"></span></a></li>
                                                @*<li class="list-inline-item"><a href="#">@p.nom</a></li>*@
                                            </ul>
                                        </td>
                                        <td>@p.descreption</td>
                                        <td>@p.date</td>
                                        <td>
                                            <ul class="view_edit_delete_list">

                                                <button type="button" class="btn btn-lg btn-green">@Html.ActionLink("Apply", "Apply")</button>

                                            </ul>
                                        </td>
                                    </tr>
                                }
</table>
</body>
</html>

Solution.Web/Views/Formation/Showapp.cshtml
@model IEnumerable<Solution.Domain.Entities.application>

@{
    ViewBag.Title = "Showapp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ShowApplication</h2>
<div class="col-lg-12">
    <div class="cnddte_fvrt_job candidate_job_reivew">
        <div class="table-responsive job_review_table">
            <table class="table">

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">

                            </th>
                            <td align="left">
                                @Html.DisplayFor(modelItem => item.Nom)
                                @Html.DisplayFor(modelItem => item.Prenom)
                            </td>
                            <td>Applicator Status:  @Html.DisplayFor(modelItem => item.ApplicationStatus)</td>

                            @*<td>Nom du Formation: @Html.DisplayFor(modelItem => item.formation.nom)</td>*@

                            <td>
                                <ul class="view_edit_delete_list">
                                    <button type="button" class="btn btn-lg btn-success">
                                        @Html.ActionLink("Accept", " Confirmer", new { id=item.AppId })
                                    </button>

                                    <button type="button" class="btn btn-lg btn-danger">@Html.ActionLink("Reject", " Confirmer", new {id=item.AppId })</button>
                                    <button type="button" class="btn btn-lg btn-danger">
                                        @Html.ActionLink("X", "Supprimer", new { id=item.AppId })
                                    </button>



                                </ul>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>

Solution.Web/Views/Formation/Supprimer.cshtml
@model Solution.Domain.Entities.application
@{
    ViewBag.Title = "Supprimer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Supprimer</h2>

<div class="row">
    <div class="col-xl-8">
        <h3>Are you sure you want to delete this?</h3>
        <div>
            @*
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Nom)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Nom)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Prenom)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Prenom)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.OfferId)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.OfferId)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CandId)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CandId)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.ApplicationStatus)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ApplicationStatus)
                    </dd>
                   </dl>
            *@
            @*  <dt>
                    @Html.DisplayNameFor(model => model.TestId)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TestId)
                </dd>
            *@



            <br /><br />

            <div class="col-lg-12">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-lg btn-thm" />
                        <button class="btn btn-lg btn-thm">@Html.ActionLink("Cancel", "ShowApp")</button>
                    </div>
                }
            </div>



        </div>
    </div>
</div>