Solution.Web/Controllers/Question/QuestionController.cs
using Solution.Domain.Entities;
using Solution.Service.Services;
using Solution.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Solution.Web.Controllers.Question
{
    public class QuestionController : Controller
    {
        QuestionService iqs = new QuestionService();
        FormationService ts = new FormationService();
        // GET: Question
        public ActionResult Index()
        {
            List<QuestionModel> lq = new List<QuestionModel>();
            foreach (var qm in iqs.GetAll())
            {
                QuestionModel q = new QuestionModel();
                q.qQst = qm.qQst;
                q.QstId = qm.QstId;
                q.Rep1 = qm.Rep1;
                q.Rep2 = qm.Rep2;
                q.Rep3 = qm.Rep3;
                q.Rep4 = qm.Rep4;
                q.idFormation = qm.idFormation;
                q.RepCorrect = qm.RepCorrect;
                lq.Add(q);

            }
            return View(lq);
        }

        // GET: Question/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Question/Create
        public ActionResult Create()
        {
            var formations = ts.GetMany();
            ViewBag.TestId = new SelectList(formations, "id", "nom");
            
            /*var offres = OS.GetMany();
            ViewBag.Offre_Id = new SelectList(offres, "Offre_Id", "Offre_Name");*/

            return View();
        }

        // POST: Question/Create
        [HttpPost]
        public ActionResult Create(QuestionModel qm)
        {
             question q = new question();
             q.qQst = qm.qQst;
             q.Rep1 = qm.Rep1;
             q.Rep2 = qm.Rep2;
             q.Rep3 = qm.Rep3;
             q.Rep4 = qm.Rep4;
             q.idFormation = qm.idFormation;
             q.RepCorrect = qm.RepCorrect;
             iqs.Add(q);
             iqs.Commit();
            return RedirectToAction("ShowQuestions");

        }

        public ActionResult ShowQuestions()
        {
            return View(iqs.GetMany());
        }

        [HttpPost]
        public ActionResult ShowQuestions(int id)
        {
            var list = iqs.GetQuestiontByFormation(id);


            return View(list);



        }

        // GET: Question/Edit/5
        public ActionResult Edit(int id)
        {

            question t = iqs.GetById(id);
            if (t == null)
            {
                return HttpNotFound();
            }
            return View(t);
        }

        // POST: Test/Edit/5
        [HttpPost]
        public ActionResult Edit(question p)
        {
            question p1 = iqs.GetById(p.QstId);
            p1.qQst = p.qQst;
            p1.Rep1 = p.Rep1;
            p1.Rep2 = p.Rep2;
            p1.Rep3 = p.Rep3;
            p1.Rep4 = p.Rep4;
            p1.RepCorrect = p.RepCorrect;

            if (ModelState.IsValid)
            {
                iqs.Update(p1);
                iqs.Commit();
                return RedirectToAction("ShowQuestions");
            }
            return RedirectToAction("ShowQuestions");
        }

        // GET: Question/Delete/5
        public ActionResult Delete(int id)
        {

            return View(iqs.GetById(id));
        }

        // POST: Question/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, question q)
        {
            q = iqs.GetById(id);
            iqs.Delete(q);
            iqs.Commit();
            return RedirectToAction("ShowQuestions");

        }

    }
}

Solution.Web/Views/Question/Create.cshtml
@model Solution.Web.Models.QuestionModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Create","Question",FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3>Create New Question</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <h4>Test Name</h4>
            <div class="col-md-10">
                @Html.DropDownList("idFormation", (SelectList)ViewData["TestId"])
                @Html.ValidationMessageFor(model => model.idFormation)
            </div>
        </div>

        <div class="form-group">
            <h4>Question</h4>
            <div class="col-md-10">
                @Html.EditorFor(model => model.qQst, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.qQst, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h4>Response 1</h4>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rep1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rep1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h4>Response 2</h4>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rep2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rep2, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <h4>Response 3</h4>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rep3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rep3, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <h4>Response 4</h4>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rep4, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rep4, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <h4>Correct Response</h4>
            <div class="col-md-10">
                @Html.EditorFor(model => model.RepCorrect, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RepCorrect, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p>
                <input type="submit" value="Create" class="btn btn-thm" />
                <button class="btn btn-thm">@Html.ActionLink("Back to List", "ShowQuestions")</button>
            </p>
        </div>
    </div>
    <br />
}

Solution.Web/Views/Question/Delete.cshtml
@model Solution.Domain.Entities.question
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<div class="col-xl-8">
    <h3>Are you sure you want to delete this?</h3>
    <div>

        <br /><br />

        <div class="col-lg-12">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-thm" />
                    <button class="btn btn-lg btn-thm"> @Html.ActionLink("Cancel", "ShowQuestions")</button>
                </div>
            }
        </div>



    </div>
</div>

Solution.Web/Views/Question/Edit.cshtml
@model Solution.Domain.Entities.question
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3>Edit Question</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })







        @Html.HiddenFor(model => model.QstId)

        <div class="form-group">
            <h4>Question</h4>
            <div class="col-md-10">
                @Html.EditorFor(model => model.qQst, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.qQst, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h4>Response 1</h4>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rep1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rep1, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <h4>Response 2</h4>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rep2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rep2, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <h4>Response 3</h4>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rep3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rep3, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <h4>Response 4</h4>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rep4, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rep4, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <h4>Correst Response</h4>
            <div class="col-md-10">
                @Html.EditorFor(model => model.RepCorrect, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RepCorrect, "", new { @class = "text-danger" })
            </div>
        </div>




        <div class="form-group">
            <p>
                <input type="submit" value="Save Changes" class="btn btn-thm" />
                <button class="btn btn-thm">@Html.ActionLink("Cancel", "ShowQuestions")</button>
            </p>
        </div>
    </div>

}

Solution.Web/Views/Question/ShowQuestions.cshtml
@model IEnumerable<Solution.Domain.Entities.question>
@{
    ViewBag.Title = "ShowQuestions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br />

<h2>Show Questions</h2>
<section>
    <br /><br />
          <p>

              <class="h3 mb-1 text-gray-800">
                  <button class="btn btn-light "> @Html.ActionLink("Create New", "Create")</button>
                  <button class="btn btn-light"> @Html.ActionLink("Go back", "../Test/ShowTests")</button>
          </p>
    <main>
        <div class="container-fluid mb-5">

            <!--Section: Basic examples-->


            <div class="row">

                <div class="col-md-12">

                    <div class="card">
                        <div class="card-body">

                            <table id="datatables" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.idFormation)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.qQst)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Rep1)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Rep2)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Rep3)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Rep4)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.RepCorrect)
                                        </th>

                                        <th></th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach (var item in Model)
                                    {

                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.idFormation)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.qQst)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Rep1)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Rep2)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Rep3)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Rep4)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.RepCorrect)
                                            </td>

                                            <td>
                                                <button class="btn btn-light">@Html.ActionLink("Edit", "Edit", new { id = item.QstId })</button>

                                                <button class="btn btn-light">@Html.ActionLink("Delete", "Delete", new { id = item.QstId })</button>
                                            </td>
                                        </tr>

                                    }
                                </tbody>

                            </table>
                        </div>
                    </div>

                </div>

            </div>

</section>
<!--Section: Basic examples-->
                </div>
            </main>