Solution.Web/Controllers/Formation/TestController.cs
using Solution.Domain;
using Solution.Domain.Entities;
using Solution.Service.Services;
using Solution.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Solution.Web.Controllers.Formation
{
    public class TestController : Controller
    {
        FormationService cs = new FormationService();
        QuestionService iqs = new QuestionService();
        public ActionResult Index()
        {

            /* int user = Int16.Parse(User.Identity.GetUserId());
             var q = itm.GetAll();*/
            {
                FormationModel tm = new FormationModel();
                formation c = new formation();
                List<FormationModel> l = new List<FormationModel>();
                List<question> lq = new List<question>();
                c = cs.GetAll().OrderByDescending(t => t.questions.Count).First();
                c.id = tm.id;
                tm.nom = c.nom;
              
                lq = c.questions.OrderBy(x => Guid.NewGuid()).Take(20).ToList();
                tm.questions = lq;
                l.Add(tm);

                return View(l);
            }

        }

        // GET: Test/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Test/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Test/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Test/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Test/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Test/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Test/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult TestResult()
        {
            {
                FormationModel tm = new FormationModel();
                formation c = new formation();
                List<FormationModel> l = new List<FormationModel>();
                List<question> lq = new List<question>();
                c = cs.GetAll().OrderByDescending(t => t.questions.Count).First();
                tm.nom = c.nom;
                
                lq = c.questions.OrderBy(x => Guid.NewGuid()).Take(20).ToList();
                tm.questions = lq;
                l.Add(tm);

                return View(l);
            }
        }
        public ActionResult TestLang()
        {
            {
                FormationModel tm = new FormationModel();
                formation c = new formation();
                List<FormationModel> l = new List<FormationModel>();
                List<question> lq = new List<question>();
                c = cs.GetAll().OrderByDescending(t => t.questions.Count).First();
                tm.nom = c.nom;

                lq = c.questions.OrderBy(x => Guid.NewGuid()).Take(20).ToList();
                tm.questions = lq;
                l.Add(tm);

                return View(l);
            }
        }
        public ActionResult TestPsy()
        {
            return View();
        }
    }
}

Solution.Web/Views/Test/Index.cshtml
@model IEnumerable<Solution.Web.Models.FormationModel>
@Scripts.Render("~/bundles/jquery")

@{
    ViewBag.Title = "Contact";
    Layout = "~/Areas/Administrateur/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>


<main>
    <br /> <br /><br />
    <style>
        body {
            font-family: sans-serif;
            color: #333;
        }

        #container {
            width: 400px;
            margin: auto;
        }

        h1 {
            font-size: 32px;
        }
    </style>



    <script>
        // two global variables
        var secondsRemaining;
        var intervalHandle;




        function tick() {
            // grab the h1
            var timeDisplay = document.getElementById("time");

            // turn seconds into mm:ss
            var min = Math.floor(secondsRemaining / 60);
            var sec = secondsRemaining - (min * 60);

            // add a leading zero (as a string value) if seconds less than 10
            if (sec < 10) {
                sec = "0" + sec;
            }
            // concatenate with colon
            var message = min + ":" + sec;
            // now change the display
            timeDisplay.innerHTML = message;

            // stop if down to zero
            if (secondsRemaining === 0) {
                alert("Your time is over!");
                $("#bout").click()

                clearInterval(intervalHandle);
                resetPage();
            }
            // subtract from seconds remaining
            secondsRemaining--;
        }

        function startCountdown() {
            // get contents of the "minutes" text box
            var minutes = 0.5;
            // check if not a number
            if (isNaN(minutes)) {
                alert("Please enter a number!");
                return;
            }
            // how many seconds?
            secondsRemaining = minutes * 60;
            // every second, call the "tick" function
            intervalHandle = setInterval(tick, 1000);
            // hide the form
        }

        // as soon as the page is loaded...
        $(document).ready(function () {
            // create input text box and give it an id of "minutes"
            var inputMinutes = document.createElement("input");
            inputMinutes.setAttribute("id", "minutes");
            inputMinutes.setAttribute("type", "text");
            // create a button
            var startButton = document.createElement("input");
            startButton.setAttribute("type", "button");
            startButton.setAttribute("value", "Start Countdown");
            startCountdown();

            // add to the DOM, to the div called "inputArea"
        });

    </script>
    <div id="container">


        <h1 id="time">0:00</h1>

    </div>
    @using (Html.BeginForm("Index", "Test"))
    {
        @Html.AntiForgeryToken()
        <div class="container">
            <h2 class="font-bold mt-lg-5 mb-5 pb-4"><strong>On Line Test </strong></h2>

            <!--Section: Background variants-->
            <section class="mb-5 pb-5">
                <h4 class="my-5 dark-grey-text font-bold">PS: You should answer fastly, if the countdown finishes you won't be able to answer anymore </h4>

                <div class="row">
                    <div class="col-md-6">

                        <!--Card indigo-->
                        <!--/.Card indigo-->
                        <br>
                        <!--Card pink-->
                        @foreach (var item in Model)
                        {
                            var a = 0;

                            foreach (var i in item.questions)
                            {
                                <h4>
                                    Select
                                    <input name="RepCorrect @a" type="radio" id="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.RepCorrect)" value="@Html.DisplayFor(modelItem => i.RepCorrect)" checked="checked">

                                    the correct answer
                                </h4>
                                <div class="list-group z-depth-1">
                                    <div class="list-group-item list-group-item-action flex-column align-items-start">
                                        <div class="d-flex w-100 justify-content-between">
                                            <h5 class="font-bold mb-3 mt-2">
                                                @Html.DisplayFor(modelItem => i.qQst)<br />
                                            </h5>
                                            <small class="text-muted">@a</small>
                                        </div>
                                        <p class="mb-1">
                                            <input name="group @a" type="radio" id="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.Rep1)" value="@Html.DisplayFor(modelItem => i.Rep1)">
                                            <label for="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.Rep1)">@Html.DisplayFor(modelItem => i.Rep1)</label>
                                        </p>
                                        <p class="mb-1">
                                            <input name="group @a" type="radio" id="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.Rep2)" value="@Html.DisplayFor(modelItem => i.Rep2)">
                                            <label for="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.Rep2)">
                                                @Html.DisplayFor(modelItem => i.Rep2)
                                            </label>
                                        </p>
                                        <p class="mb-1">
                                            <input name="group @a" type="radio" id="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.Rep3)" value="@Html.DisplayFor(modelItem => i.Rep3)">
                                            <label for="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.Rep3)">
                                                @Html.DisplayFor(modelItem => i.Rep3)
                                            </label>
                                        </p>
                                        <p class="mb-1">
                                            <input name="group @a" type="radio" id="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.Rep4)" value="@Html.DisplayFor(modelItem => i.Rep4)">
                                            <label for="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.Rep4)">
                                                @Html.DisplayFor(modelItem => i.Rep4)
                                            </label>
                                        </p>
                                        <small class="text-muted">Question @a</small>
                                    </div>
                                </div>

                                a++;

                            }


                        }



                        <br>

                        <input id="bout" value="confirmer" type="submit" class="btn btn-thm">
                        <script>
                                $("#bout").click(function score () {
                                    alert("Click on Ok");
                                    var i = 0;
                                    var note = 0;
                                    alert("These are your ansewrs:")
                                    for (i = 0; i < 3; i++) {
                                        alert($('input[name="group ' + i + '"]:checked').val());

                                        if ($('input[name="group ' + i + '"]:checked').val() == $('input[name="RepCorrect ' + i + '"]:checked').val()) {
                                            note++;
                                        }


                                    }
                                    alert(note);
                                    if (note < 3) {
                                        alert("Sorry you failed your test !");
                                        for (i = 0; i < 20; i++) {
                                            alert("Your process is done ! You can not go further !")
                                        }

                                    } else alert("Congratulations you succeeded !");
                                }

                                   @* document.getElementById("score").value = note;
                                    document.getElementById("ide").value = 1;*@
                                );
                        </script>

                    </div>


                    <div class="col-md-6">

                        <!--Card red-->
                        <!--/.Card red-->
                        <br>
                        <!--Card success-->
                        <!--/.Card success-->
                        <br>
                        <!--Card mdb-->
                        <!--/.Card mdb-->
                        <!--Card transparent-->
                        <!--/.Card transparent-->

                    </div>
                </div>

            </section>
            <!--Section: Background variants-->
            <!--Section: Basic examples-->
            <!--Section: Basic examples-->
            <!--Section: Docs link-->
            <section class="pb-4">

                <!--Panel-->
                <div class="card text-center">
                    <h3 class="card-header primary-color white-text">Full documentation</h3>
                    <div class="card-body">
                        <p class="card-text">Read the full documentation for these components.</p>
                        <a href="https://mdbootstrap.com/components/panels/" target="_blank" class="btn btn-primary">Learn more</a>
                    </div>
                </div>
                <!--/.Panel-->


            </section>
            <!--Section: Docs link-->

        </div>
    }

</main>

Solution.Web/Views/Test/TestLang.cshtml
@model IEnumerable<Solution.Web.Models.FormationModel>
@{
    ViewBag.Title = "TestLang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>TestLang</h2>

<script src="@Url.Content("~/Content/LayoutAcceui/")vendor/jquery/jquery.min.js"></script>

<main>
    <br /> <br /><br />
    <style>
        body {
            font-family: sans-serif;
            color: #333;
        }

        #container {
            width: 400px;
            margin: auto;
        }

        h1 {
            font-size: 32px;
    </style>

    <script>
        // two global variables
        var secondsRemaining;
        var intervalHandle;




        function tick() {
            // grab the h1
            var timeDisplay = document.getElementById("time");

            // turn seconds into mm:ss
            var min = Math.floor(secondsRemaining / 60);
            var sec = secondsRemaining - (min * 60);

            // add a leading zero (as a string value) if seconds less than 10
            if (sec < 10) {
                sec = "0" + sec;
            }
            // concatenate with colon
            var message = min + ":" + sec;
            // now change the display
            timeDisplay.innerHTML = message;

            // stop if down to zero
            if (secondsRemaining === 0) {
                alert("Your time is over!");
                $("#bout").click()

                clearInterval(intervalHandle);
                resetPage();
            }
            // subtract from seconds remaining
            secondsRemaining--;
        }

        function startCountdown() {
            // get contents of the "minutes" text box
            var minutes = 0.5;
            // check if not a number
            if (isNaN(minutes)) {
                alert("Please enter a number!");
                return;
            }
            // how many seconds?
            secondsRemaining = minutes * 60;
            // every second, call the "tick" function
            intervalHandle = setInterval(tick, 1000);
            // hide the form
        }

        // as soon as the page is loaded...
        $(document).ready(function () {
            // create input text box and give it an id of "minutes"
            var inputMinutes = document.createElement("input");
            inputMinutes.setAttribute("id", "minutes");
            inputMinutes.setAttribute("type", "text");
            // create a button
            var startButton = document.createElement("input");
            startButton.setAttribute("type", "button");
            startButton.setAttribute("value", "Start Countdown");
            startCountdown();

            // add to the DOM, to the div called "inputArea"
        });

    </script>
    <div id="container">


        <h1 id="time">0:00</h1>

    </div>
    @using (Html.BeginForm("TestPsy", "Test"))
    {
        @Html.AntiForgeryToken()
        <div class="container">
            <h2 class="font-bold mt-lg-5 mb-5 pb-4"><strong>Psychotechnical Test </strong></h2>

            <!--Section: Background variants-->
            <section class="mb-5 pb-5">
                <h4 class="my-5 dark-grey-text font-bold">PS: You should answer fastly, if the countdown finishes you won't be able to answer anymore </h4>

                <div class="row">
                    <div class="col-md-6">

                        <!--Card indigo-->
                        <!--/.Card indigo-->
                        <br>
                        <!--Card pink-->
                        @foreach (var item in Model)
                        {
                            var a = 0;

                            foreach (var i in item.questions)
                            {
                                <h4>
                                    Select
                                    <input name="RepCorrect @a" type="radio" id="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.RepCorrect)" value="@Html.DisplayFor(modelItem => i.RepCorrect)" checked="checked">

                                    the correct answer
                                </h4>
                                <div class="list-group z-depth-1">
                                    <div class="list-group-item list-group-item-action flex-column align-items-start">
                                        <div class="d-flex w-100 justify-content-between">
                                            <h5 class="font-bold mb-3 mt-2">
                                                @Html.DisplayFor(modelItem => i.qQst)<br />
                                            </h5>
                                            <small class="text-muted">@a</small>
                                        </div>
                                        <p class="mb-1">
                                            <input name="group @a" type="radio" id="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.Rep1)" value="@Html.DisplayFor(modelItem => i.Rep1)">
                                            <label for="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.Rep1)">@Html.DisplayFor(modelItem => i.Rep1)</label>
                                        </p>
                                        <p class="mb-1">
                                            <input name="group @a" type="radio" id="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.Rep2)" value="@Html.DisplayFor(modelItem => i.Rep2)">
                                            <label for="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.Rep2)">
                                                @Html.DisplayFor(modelItem => i.Rep2)
                                            </label>
                                        </p>
                                        <p class="mb-1">
                                            <input name="group @a" type="radio" id="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.Rep3)" value="@Html.DisplayFor(modelItem => i.Rep3)">
                                            <label for="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.Rep3)">
                                                @Html.DisplayFor(modelItem => i.Rep3)
                                            </label>
                                        </p>
                                        <p class="mb-1">
                                            <input name="group @a" type="radio" id="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.Rep4)" value="@Html.DisplayFor(modelItem => i.Rep4)">
                                            <label for="@Html.DisplayFor(modelItem => i.QstId)@Html.DisplayFor(modelItem => i.Rep4)">
                                                @Html.DisplayFor(modelItem => i.Rep4)
                                            </label>
                                        </p>
                                        <small class="text-muted">Question @a</small>
                                    </div>
                                </div>

                                a++;

                            }


                        }



                        <br>

                        <input id="bout" value="confirmer" type="submit" class="btn btn-thm">
                        <script>
                                $("#bout").click(function () {
                                    alert("Click on Ok");
                                    var i = 0;
                                    var note = 0;
                                    alert("These are your ansewrs:")
                                    for (i = 0; i < 3; i++) {
                                        alert($('input[name="group ' + i + '"]:checked').val());

                                        if ($('input[name="group ' + i + '"]:checked').val() == $('input[name="RepCorrect ' + i + '"]:checked').val()) {
                                            note++;
                                        }


                                    }
                                    alert(note);
                                    if (note < 3) {
                                        alert("Sorry you failed your test !");
                                        for (i = 0; i < 20; i++) {
                                            alert("Your process is done ! You can not go further !")
                                        }

                                    } else alert("Congratulations you succeeded !");
                                }

                                   @* document.getElementById("score").value = note;
                                    document.getElementById("ide").value = 1;*@
                                );
                        </script>

                    </div>


                    <div class="col-md-6">

                        <!--Card red-->
                        <!--/.Card red-->
                        <br>
                        <!--Card success-->
                        <!--/.Card success-->
                        <br>
                        <!--Card mdb-->
                        <!--/.Card mdb-->
                        <!--Card transparent-->
                        <!--/.Card transparent-->

                    </div>
                </div>

            </section>
            <!--Section: Background variants-->
            <!--Section: Basic examples-->
            <!--Section: Basic examples-->
            <!--Section: Docs link-->
            <section class="pb-4">

                <!--Panel-->
                <div class="card text-center">
                    <h3 class="card-header primary-color white-text">Full documentation</h3>
                    <div class="card-body">
                        <p class="card-text">Read the full documentation for these components.</p>
                        <a href="https://mdbootstrap.com/components/panels/" target="_blank" class="btn btn-primary">Learn more</a>
                    </div>
                </div>
                <!--/.Panel-->


            </section>
            <!--Section: Docs link-->

        </div>
    }

</main>